language: php

dist: trusty

php:
  - '5.3'
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4snapshot'
  - hhvm
  - nightly

matrix:
  include:
    - php: '5.3'
      dist: precise

sudo: false

before_script:
  - if [[ $TRAVIS_PHP_VERSION = 'nightly' ]]; then curl -sSfL -o ~/.phpenv/versions/hhvm/bin/phpunit https://phar.phpunit.de/phpunit-5.7.phar; fi
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpcs --standard=psr2 src/
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - if [[ $TRAVIS_PHP_VERSION != 'hhvm' && $TRAVIS_PHP_VERSION != '7.0' ]]; then php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover; fi

after_success:
  - if [ $TRAVIS_PHP_VERSION = '5.6' ] && [ ! -z $TRAVIS_TAG ] && [ $TRAVIS_PULL_REQUEST = 'false' ]; then ./generate-doc.sh; fi
